### PR TITLE
Remove items

### PR DESCRIPTION
**Pull request by vikasgarghb**
@joshuacc See any issue here?

### CODE REVIEW

**Comment by joshuacc** [comment]
Looks fine at a glance. Have you tested it out in IE8?

**Comment by vikasgarghb** [comment]
Not yet. Haven't tested in IE8 but will do so now.

**Comment by vikasgarghb** [comment]
@joshuacc It works fine on IE8.

**Comment by joshuacc** [comment]
@vikasgarghb Closing for staleness.

**Comment by Pickra** [comment]
😿

**Pull request closed without merging**
